#1.	Top 5 Best-Selling Products
select p.ProductName, sum(o.Quantity) as TotalSold from Orders o join Products p on o.ProductID = p.ProductID group by o.ProductID order by TotalSold desc limit 5;

#2.	Total Revenue Generated by Each Product Category
select p.Category, sum(o.Quantity * p.Price) as TotalRevenue from Orders o join Products p on o.ProductID = p.ProductID group by p.Category;

#3.	Average Rating of Each Product
select p.ProductName, round(avg(pr.Rating), 2) as AverageRating from ProductReviews pr join Products p on pr.ProductID = p.ProductID group by pr.ProductID;

#4.	Check Product Stock Status (Low Stock Alert less than 50) 
select ProductName, Stock from Products where Stock < 50;

#5.	Most Active Customers (Highest Number of Orders)
select c.Name, count(o.OrderID) as OrderCount from Customers c join Orders o on c.CustomerID = o.CustomerID group by c.CustomerID order by OrderCount desc;

#6.	List of Products with No Reviews
select p.ProductName from Products p left join ProductReviews pr on p.ProductID = pr.ProductID where pr.ReviewID is null;
 
#7.	Top Reviewed Products (Most Number of Reviews)
select p.ProductName, count(pr.ReviewID) as ReviewCount from ProductReviews pr join Products p on pr.ProductID = p.ProductID group by pr.ProductID order by ReviewCount desc;

#8.	Name of the customers Who Spent More Than ₹2000 
select c.Name, sum(o.Quantity * p.Price) as TotalSpent from Customers c join Orders o on c.CustomerID = o.CustomerID join Products p on o.ProductID = p.ProductID group by c.CustomerID having TotalSpent > 2000;

#9.Find Customers Who Bought More Than 3 Different Products 
select c.Name, count(distinct o.ProductID) as ProductCount from Customers c join Orders o on c.CustomerID = o.CustomerID group by c.CustomerID having ProductCount > 3;

#10.List of Products Never Ordered 
select p.ProductName from Products p left join Orders o on p.ProductID = o.ProductID where o.OrderID is null;

#11.Average Order Quantity Per Product 
select p.ProductName, round(avg(o.Quantity), 0) as AvgQuantity from Orders o join Products p on o.ProductID = p.ProductID group by o.ProductID;

#12.Customer Product Feedback Summary 
select c.Name, p.ProductName, count(pr.ReviewID) as TotalReviews, round(avg(pr.Rating), 2) as AvgRating from Customers c join Orders o on c.CustomerID = o.CustomerID join Products p on o.ProductID = p.ProductID left join ProductReviews pr on p.ProductID = pr.ProductID and pr.CustomerID = c.CustomerID group by c.Name, p.ProductName;
 
#13.Average Age of Customers Per City 
select City, round(avg(Age), 2) as AvgAge from Customers group by City;

#14.Most Expensive Product in Each Category 
select category, productname, price from products p where price = (select max(price) from products p2 where p2.category = p.category);

#15.Monthly Sales Report
 select year(o.OrderDate) as Year, month(o.OrderDate) as Month, sum(o.Quantity * p.Price) as TotalSales from Orders o join Products p on o.ProductID = p.ProductID group by year(o.OrderDate), month(o.OrderDate) order by Year, Month;